name: webapp
type: nodejs:10
disk: 2048

dependencies:
    nodejs:
        yarn: "*"
        platformsh-config: "*"

hooks:
    build: |
        set -e

        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
        chmod +x jq

        yarn global add @vue/cli
        yarn install

        # Build the application for production
        yarn run build

        # mv dist webapp

        # Move the configuration file into place.
        # This file uses the Platform.sh Node.js Config Reader
        # to get the host addresses of the relationships defined below
        # mv public _public

        CORTEZA_APPS="admin auth compose messaging"

        mkdir service-repos

        for MICROAPP in $CORTEZA_APPS; do
            echo "\n#########################################"
            echo "# Building corteza-webapp-${MICROAPP}"
            echo "#########################################\n"

            git clone "https://github.com/cortezaproject/corteza-webapp-${MICROAPP}.git" service-repos/${MICROAPP}
            cd service-repos/${MICROAPP}
            yarn install --prefer-offline
            yarn build
            cd ${PLATFORM_APP_DIR}
            mv service-repos/${MICROAPP}/dist dist/${MICROAPP}
            rm -rf service-repos/${MICROAPP}
        done;

        rm -rf service-repos .cache/yarn


    deploy:
        set -e

        cp -R dist/* webapp/

        PRIMARY_ROUTE=$(
            echo $PLATFORM_ROUTES | base64 -d | ${PLATFORM_APP_DIR}/jq -r \
            '. as $routes |
                keys | .[] |
                select($routes[.].primary) | .
            '
        )
        PRIMARY_ROUTE="${PRIMARY_ROUTE:8:-1}"

        echo "Creating config.js..."
        /bin/cat << EOF > webapp/config.js
        // Config generated at runtime
        window.SystemAPI = \`https://system.api.${PRIMARY_ROUTE}\`
        window.MessagingAPI = \`https://messaging.api.${PRIMARY_ROUTE}\`
        window.ComposeAPI = \`https://compose.api.${PRIMARY_ROUTE}\`
        EOF

        cat webapp/config.js

mounts:
    'webapp':
        source: local
        source_path: webapp

web:
    commands:
      start: sleep infinity
    upstream:
        socket_family: tcp
        protocol: http
    locations:
        "/":
            root: "webapp"
            passthru: true
            index: ['index.html']


relationships:
    systemapi: "server:http"
    messagingapi: "server:http"
    composeapi: "server:http"
